version: '2'
services:

       php:
        image: webapp
        environment:
           - DB_HOST=${HOST}
           - DB_USERNAME=${USERNAME}
           - DB_PASSWORD=${PASSWORD}
           - DB_NAME=crud_laundry
        volumes:
           - ./:/app
        working_dir: /app

       web:
        image: nginx-webapps
        volumes:
           - ./:/app
        depends_on:
           - db
        ports:
           - "80:80"

       db:
        container_name: mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes: 
           - ./:/app/db-tugas5
        environment:
           - MYSQL_ROOT_PASSWORD=${ROOT}
           - MYSQL_USERNAME=${USERNAME}
           - MYSQL_PASSWORD=${PASSWORD}
           - MYSQL_DATABASE=crud_laundry
        ports:
           - "3306:3306"
